---
version: '3.4'
services:
  febuddybot:
    image: febuddybot:dev
    build: .
    container_name: febuddybot
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - /home/febuddybot/botLogs/:/app/logs/
      - F:\Github-Repos\FE-BUDDYBot-ContainerData\botLogs:/app/logs/
  
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    volumes:
      - /home/febuddybot/mongoDB/:/data/db
      - F:\Github-Repos\FE-BUDDYBot-ContainerData\mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOTUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOTPASSWORD}
  
  # SHOULD ONLY BE USED FOR PRIVATE DEVELOPMENT!
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ADMINUSERNAME}:${ADMINPASSWORD}@mongo:27017/